name: Development build

on:
  push:
    branches:
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      projectName: ${{ steps.project_details.outputs.project_name }}
      projectVersion: ${{ steps.project_details.outputs.project_version }}

    steps:
      - uses: actions/checkout@v4
      - name: Extract project details
        id: project_details
        run: |
          echo "PROJECT_NAME=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Build Module
        run: |
          mvn -T 1C -B package --file /home/runner/work/CloudNet-ExternalProtect/pom.xml

      - name: Upload artifact
        env:
          projectName: ${{ needs.setup.outputs.projectName }}
          projectVersion: ${{ needs.setup.outputs.projectVersion }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.projectName }}-${{ env.projectVersion }}-b${{ github.run_number }}
          path: target/${{ env.projectName }}-${{ env.projectVersion }}.jar
